{% set name = "pymt_waves" %}
{% set version = "0.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - cem

  run:
    - python
    - setuptools
    - pymt
    - cem

test:
  requires:
    - bmi-tester
  imports:
    - pymt
    - waves
  commands:
    - mmd-stage Waves .
    - bmi-test waves:Waves --infile=waves.txt

about:
  summary: Python package that wraps the Waves BMI.
  home: https://github.com/mcflugen/pymt_waves
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_waves
