build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries:
  - bmi_waves
  library_dirs: []
  undef_macros: []
info:
  github_username: mcflugen
  plugin_author: Eric Hutton
  plugin_license: MIT
  summary: PyMT plugin for Waves
library:
  entry_point: Waves=waves:Waves
  language: c
  register: register_bmi_waves
plugin:
  name: waves
  requirements:
  - cem
